### ISSUE TITLE
Kernel Drivers signing for El Capitan

### ISSUE THREAD

**Issue by iancdavidson** [RJVB/OS-X-SAT-SMART-Driver#4]
Could the drivers be signed so user doesn't need kernel dev mode enabled in El Capitan?
https://developer.apple.com/library/mac/documentation/Security/Conceptual/System_Integrity_Protection_Guide/KernelExtensions/KernelExtensions.html

**Comment by RJVB** [comment]
You'd better take this up with the author of the original driver from whom I forked this repository (which I haven't been maintaining at all for a while now). See  https://github.com/kasbert/OS-X-SAT-SMART-Driver

I don't have a signing certificate and don't intend to pay Apple even once in order to be able to install things on _my_ machines. 

That said, I have the impression that the driver is in a list of known exceptions on 10.9; maybe kasbert knows more about that.

**Comment by iancdavidson** [comment]
Thanks for your reply. I saw the fork and have used the new free El Capitan signed version made by binary fruit.  It works. http://binaryfruit.com/drivedx/kb#external-drives-support-osx-el-capitan

**Comment by porg** [comment]
I use the signed driver version 0.8.1 kindly provided by the DriveDx folks,
and it works fine under macOS Mojave 10.14.6
in smartmontools 7.0 2018-12-30 r4883
